WiP

diff --git a/install/usr/bin/aurex-mirror b/install/usr/bin/aurex-mirror
--- a/install/usr/bin/aurex-mirror
+++ b/install/usr/bin/aurex-mirror
@@ -18,12 +18,17 @@
 # 51 Franklin St, Fifth Floor, Boston MA 02110-1301 USA
 # --------
 
-usage(){
-	echo "Usage: $(basename "$0") CONF_NAME [MIRROR_DIRECTORY]" >&2
+die(){
+	echo "$1" >&2
 	exit 1
 }
 
+usage(){
+	die "Usage: $(basename "$0") CONF_NAME [MIRROR_DIRECTORY]"
+}
+
 [ "$1" ] || usage
+BASE_NAME="$1"
 CONF_CFG="/etc/aurex-mirror/conf.d/${1}.cfg"
 [ -r "$CONF_CFG" ] || usage
 . $CONF_CFG
@@ -53,4 +58,18 @@ esac
 
 [ "$DIST_LIST" -a "$SECT_LIST" -a "$ARCH_HOST" -a "$ARCH_LIST" -a "$ROOT_DIR" ] || usage
 
-debmirror --nosource --ignore-small-errors --ignore-release-gpg --method=$METHOD --md5sums --progress --host=$ARCH_HOST --root=$ROOT_DIR --dist=$DIST_LIST --section=$SECT_LIST --arch=$ARCH_LIST $MIRROR_DIR
+if [ $(id -u) -eq 0 ] || echo " $(groups) " |grep -q " aurex-mirror " ; then
+	rc=0
+	DATESTAMP="$(date "+%b %d %Y %T") $HOSTNAME  ${BASE_NAME}: "
+	LAST_RUN="/var/log/aurex-mirror/${BASE_NAME}.last-run"
+	LOG_FILE="/var/log/aurex-mirror/${BASE_NAME}.log"
+	echo "$DATESTAMP START in $MIRROR_DIR ($METHOD,$ARCH_HOST)" >> $LOG_FILE
+
+	debmirror --nosource --ignore-small-errors --ignore-release-gpg --method=$METHOD --md5sums --progress --host=$ARCH_HOST --root=$ROOT_DIR --dist=$DIST_LIST --section=$SECT_LIST --arch=$ARCH_LIST $MIRROR_DIR 2>$LAST_RUN || rc=$?
+
+	DATESTAMP="$(date "+%b %d %Y %T") $HOSTNAME  ${BASE_NAME}: "
+	echo "$DATESTAMP END (Exit status: $rc)" >> $LOG_FILE
+	
+else
+	die "ERROR: Only members of system group 'aurex-mirror' can use this program"
+fi
